version: "2"

services:
api: 
    build: compose/service
    ports:	
    - "8080:5000"

web:
     build: .
     ports:
     - "8080:5000"

db:
     image: mysql
     container_name: mysql
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: db
     MYSQL_USER: javier
     MYSQL_PASSWORD: contraseña
