version: '2'
services:

  service:
    build: compose/service/.
    ports:
      - "80:5000"
    links:
      - db
    depends_on:
      - db

  db:
    build: compose/db/.
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: password
