Vagrant.configure("2") do |config|
  config.vm.define "ServicioWeb" do |serviceObject|
    serviceObject.vm.box = 'azure'

    # Local SSH key to connect to Vagrant Box
    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'
    serviceObject.vm.provider :azure do |azure, override|
      
      # Set a territory
      azure.location="westeurope"

      # Set a Name of the resource group and the virtual machine
      azure.resource_group_name="CC-Master"
      azure.vm_name="ServicioWebVM"

      # Set the operating system of the virtual machine   
      azure.vm_image_urn="OpenLogic:CentOS:7.3:latest"

      # set the variables
      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end

     # Provision the virtual machine
      ServicioWeb.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
      end
 end

 config.vm.define "BaseDatos" do |serviceImage|
    serviceImage.vm.box = 'azure'

    # Local SSH key to connect to Vagrant Box
    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'
    serviceImage.vm.provider :azure do |azure, override|
      
      #Set a territory
      azure.location="westeurope"

      # Set a Name of the resource group and the virtual machine
      azure.resource_group_name="CC-Master"
      azure.vm_name="BaseDatosVM"

      # Set the operating system of the virtual machine
      azure.vm_image_urn="OpenLogic:CentOS:7.3:latest"

      # set the variables
      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end
 
      # Provision the virtual machine
      BaseDatos.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
      end
  end

end
