# Variables 
AZURE_TENANT_ID = ENV['AZURE_TENANT_ID']
AZURE_CLIENT_ID = ENV['AZURE_CLIENT_ID']
AZURE_CLIENT_SECRET = ENV['AZURE_CLIENT_SECRET']
AZURE_SUBSCRIPTION_ID = ENV['AZURE_SUBSCRIPTION_ID']

Vagrant.configure("2") do |config|
  config.vm.define "ServicioWeb" do |serviceWeb|
    serviceWeb.vm.box = 'azure'

    # Local SSH key to connect to Vagrant Box
    serviceWeb.ssh.private_key_path = '~/.ssh/id_rsa'
    serviceWeb.vm.provider :azure do |azure, override|
      
      # Set a territory
      azure.location="westeurope"

      # Set a Name of the resource group and the virtual machine
      azure.resource_group_name="CC-Master"
      azure.vm_name="ServicioWebVM"

      # Set the operating system of the virtual machine   
      azure.vm_image_urn="OpenLogic:CentOS:7.3:latest"

      # set the variables
      azure.tenant_id = AZURE_TENANT_ID
      azure.client_id = AZURE_CLIENT_ID
      azure.client_secret = AZURE_CLIENT_SECRET
      azure.subscription_id = AZURE_SUBSCRIPTION_ID
    end

     # Provision the virtual machine Ansible
      ServicioWeb.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
      end
 end

 config.vm.define "BaseDatos" do |serviceBase|
    serviceImage.vm.box = 'azure'

    # Local SSH key to connect to Vagrant Box
    serviceBase.ssh.private_key_path = '~/.ssh/id_rsa'
    serviceBase.vm.provider :azure do |azure, override|
      
      #Set a territory
      azure.location="westeurope"

      # Set a Name of the resource group and the virtual machine
      azure.resource_group_name="CC-Master"
      azure.vm_name="BaseDatosVM"

      # Set the operating system of the virtual machine
      azure.vm_image_urn="OpenLogic:CentOS:7.3:latest"

      # set the variables
      azure.tenant_id = AZURE_TENANT_ID
      azure.client_id = AZURE_CLIENT_ID
      azure.client_secret = AZURE_CLIENT_SECRET
      azure.subscription_id = AZURE_SUBSCRIPTION_ID
    end
  end
      # Provision the virtual machine chef-solo
        config.vm.provision "chef_solo" do |chef|
        chef.cookbooks_path = "BaseDatos"
        end

end
