Vagrant.configure("2") do |config|
  config.vm.define "cc-preguntas" do |serviceObject|
    serviceObject.vm.box = 'azure'

    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|
      
      #Set a territory
      azure.location="westeurope"

      azure.resource_group_name="CC-Proyecto-Javier"
      azure.vm_name="cc-preguntas"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end
      serviceObject.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end

 end

config.vm.define "cc-lugares" do |serviceImage|
    serviceImage.vm.box = 'azure'

    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|
      
      #Set a territory
      azure.location="westeurope"

      azure.resource_group_name="CC-Proyecto-Javier"
      azure.vm_name="cc-lugares"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
     
      serviceImage.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
	end
  end

end
